# Generated by Django 4.2.7 on 2024-02-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0002_alter_task_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="group",
            field=models.CharField(
                choices=[
                    ("0", "College"),
                    ("1", "Work"),
                    ("2", "Bills"),
                    ("3", "Other"),
                ],
                default=1,
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Group",
        ),
    ]
