# Generated by Django 4.2.7 on 2024-03-06 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0003_alter_task_group_delete_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="Groups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="task",
            name="time",
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name="task",
            name="group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedule.groups",
            ),
        ),
    ]
