# Generated by Django 4.2.7 on 2024-03-06 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0004_groups_task_date_task_time_alter_task_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="group",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedule.groups",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="time",
            field=models.TimeField(default=None, null=True),
        ),
    ]
