# Generated by Django 4.2.7 on 2024-03-06 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schedule", "0005_alter_task_date_alter_task_group_alter_task_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="groups",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_group",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_task",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
